# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import accounts_pb2 as accounts__pb2


class AccountsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.NewAccount = channel.unary_unary(
        '/accounts.Accounts/NewAccount',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.AccountFromKey = channel.unary_unary(
        '/accounts.Accounts/AccountFromKey',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.GetAllAccounts = channel.unary_unary(
        '/accounts.Accounts/GetAllAccounts',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.MakeEncodingSafe = channel.unary_unary(
        '/accounts.Accounts/MakeEncodingSafe',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.RecoverSafeEncoding = channel.unary_unary(
        '/accounts.Accounts/RecoverSafeEncoding',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.String = channel.unary_unary(
        '/accounts.Accounts/String',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.Bytes = channel.unary_unary(
        '/accounts.Accounts/Bytes',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )
    self.ReadAccountFromMemory = channel.unary_unary(
        '/accounts.Accounts/ReadAccountFromMemory',
        request_serializer=accounts__pb2.GeneralRequest.SerializeToString,
        response_deserializer=accounts__pb2.GeneralResponse.FromString,
        )


class AccountsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def NewAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AccountFromKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllAccounts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MakeEncodingSafe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RecoverSafeEncoding(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def String(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Bytes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadAccountFromMemory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'NewAccount': grpc.unary_unary_rpc_method_handler(
          servicer.NewAccount,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'AccountFromKey': grpc.unary_unary_rpc_method_handler(
          servicer.AccountFromKey,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'GetAllAccounts': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllAccounts,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'MakeEncodingSafe': grpc.unary_unary_rpc_method_handler(
          servicer.MakeEncodingSafe,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'RecoverSafeEncoding': grpc.unary_unary_rpc_method_handler(
          servicer.RecoverSafeEncoding,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'String': grpc.unary_unary_rpc_method_handler(
          servicer.String,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'Bytes': grpc.unary_unary_rpc_method_handler(
          servicer.Bytes,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
      'ReadAccountFromMemory': grpc.unary_unary_rpc_method_handler(
          servicer.ReadAccountFromMemory,
          request_deserializer=accounts__pb2.GeneralRequest.FromString,
          response_serializer=accounts__pb2.GeneralResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'accounts.Accounts', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
