# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chain.proto',
  package='chain',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63hain.proto\x12\x05\x63hain\"!\n\x0eGeneralRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\"\n\x0fGeneralResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8f\x03\n\x05\x43hain\x12=\n\nGetBalance\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x12\x38\n\x05\x42ytes\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x12\x39\n\x06String\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x12\x46\n\x13ReadChainFromMemory\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x12\x43\n\x10QueryTransaction\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x12\x45\n\x12GetNumTransactions\x12\x15.chain.GeneralRequest\x1a\x16.chain.GeneralResponse\"\x00\x62\x06proto3')
)




_GENERALREQUEST = _descriptor.Descriptor(
  name='GeneralRequest',
  full_name='chain.GeneralRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='chain.GeneralRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=55,
)


_GENERALRESPONSE = _descriptor.Descriptor(
  name='GeneralResponse',
  full_name='chain.GeneralResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='chain.GeneralResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['GeneralRequest'] = _GENERALREQUEST
DESCRIPTOR.message_types_by_name['GeneralResponse'] = _GENERALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralRequest = _reflection.GeneratedProtocolMessageType('GeneralRequest', (_message.Message,), dict(
  DESCRIPTOR = _GENERALREQUEST,
  __module__ = 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.GeneralRequest)
  ))
_sym_db.RegisterMessage(GeneralRequest)

GeneralResponse = _reflection.GeneratedProtocolMessageType('GeneralResponse', (_message.Message,), dict(
  DESCRIPTOR = _GENERALRESPONSE,
  __module__ = 'chain_pb2'
  # @@protoc_insertion_point(class_scope:chain.GeneralResponse)
  ))
_sym_db.RegisterMessage(GeneralResponse)



_CHAIN = _descriptor.ServiceDescriptor(
  name='Chain',
  full_name='chain.Chain',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=94,
  serialized_end=493,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='chain.Chain.GetBalance',
    index=0,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Bytes',
    full_name='chain.Chain.Bytes',
    index=1,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='String',
    full_name='chain.Chain.String',
    index=2,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadChainFromMemory',
    full_name='chain.Chain.ReadChainFromMemory',
    index=3,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='QueryTransaction',
    full_name='chain.Chain.QueryTransaction',
    index=4,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNumTransactions',
    full_name='chain.Chain.GetNumTransactions',
    index=5,
    containing_service=None,
    input_type=_GENERALREQUEST,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAIN)

DESCRIPTOR.services_by_name['Chain'] = _CHAIN

# @@protoc_insertion_point(module_scope)
